apiVersion: v1
kind: Secret
metadata:
  name: aisysrev-secret
  namespace: aisysrev
type: Opaque
stringData:
  DB_URL: postgresql+asyncpg://<user>:<password>@<db-host>:5432/<database-name>?ssl=require
  OIDC_CLIENT_ID: <entity-id-from-sp-registry>
  OIDC_CLIENT_SECRET: <client-secret-from-sp-registry>
  SECRET_KEY: <random-hex-string>
  STORAGE_BACKEND: s3
  S3_ENDPOINT_URL: https://s3.datacloud.helsinki.fi
  S3_BUCKET: <bucket-name>
  S3_ACCESS_KEY_ID: <access-key>
  S3_SECRET_ACCESS_KEY: <secret-access-key>
  S3_REGION: us-east-1 #All information for DataCloud is stored at University of Helsinki which means region here is insignificant.

---

apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  namespace: aisysrev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths": {"quay.io": {"username": "<username>","password": "<password>","auth":"base64("username:password")"}}}