apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aisysrev-redis-pvc
  namespace: aisysrev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: data-1