FROM node:22-alpine AS client

WORKDIR /app
ENV PYTHONPATH=/app

COPY client/package.json client/package-lock.json ./

RUN npm ci

COPY client/eslint.config.js .
COPY client/index.html .
COPY client/postcss.config.js .
COPY client/tailwind.config.js .
COPY client/tsconfig.json .
COPY client/tsconfig.app.json .
COPY client/tsconfig.node.json .
COPY client/vite.config.ts .

COPY client/public ./public
COPY client/src ./src

EXPOSE 3000
CMD ["npm", "run", "dev"]

FROM python:3.11-alpine AS server

WORKDIR /app

RUN addgroup -S celerygroup && adduser -S celeryuser -G celerygroup

COPY server/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY server/ .

USER celeryuser

EXPOSE 8080

CMD ["fastapi", "dev", "src/main.py", "--host", "0.0.0.0", "--port", "8080"]