version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"

  postgres:
    image: postgres:alpine
    container_name: llm_screening_poc_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
