services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: client
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: package.json
    depends_on:
      - backend


  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: server
    environment:
      PYTHONPATH: /app
      APP_ENV: ${APP_ENV:-dev}
      DEV_DB_URL: "postgresql+asyncpg://your_username:your_password@postgres:5432/your_database_dev"
      TEST_DB_URL: "postgresql+asyncpg://your_username:your_password@postgres:5432/your_database_test"
      PROD_DB_URL: "postgresql+asyncpg://your_username:your_password@postgres:5432/your_database_prod"
      CELERY_BROKER_URL: redis://redis:6379/0
      REDIS_URL: redis://redis:6379/0
      MINIO_ROOT_USER: your_username
      MINIO_ROOT_PASSWORD: minio-secret-key
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
            - dist/
            - migrations/
            - server/migrations/
        - action: rebuild
          path: package.json
    depends_on:
      - postgres
      - minio
      - redis

  postgres:
    image: postgres:alpine@sha256:fbe21607052bb5c298674f2fd8cf044a63aa3ddf50b81627f894f91f40f50bcb
    container_name: llm_screening_poc_dev_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d

  adminer:
      image: adminer:5.3.0@sha256:6bc678e77abcd8c7f34133f4903a4be485ec38b17df3d40a845ee56af0fcb32a
      restart: always
      ports:
        - 8081:8080

  minio:
    image: minio/minio:latest@sha256:064117214caceaa8d8a90ef7caa58f2b2aeb316b5156afe9ee8da5b4d83e12c8
    container_name: llm_screening_poc_minio
    environment:
      MINIO_ROOT_USER: your_username
      MINIO_ROOT_PASSWORD: minio-secret-key
    command: server --console-address ":9001" /csv_data /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_csv_data:/csv_data
      - minio_data:/data

  redis:
    image: redis:7.4.5-alpine@sha256:0c0142c3cd69bc030ea09fecfa1c1c0c7d0e7d6081be6bb4957804f23d2cf57a
    container_name: llm_screening_poc_redis
    privileged: true
    volumes: 
      - redis_data:/data
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: celery
    environment:
      PYTHONPATH: /app
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - backend
      - redis
    volumes:
      - ./server:/app

  flower:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: server
    command: celery -A src.worker flower --port=5555
    environment:
      PYTHONPATH: /app
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
  minio_csv_data:
  minio_data:
  redis_data: