services:
  frontend:
    container_name: frontend_prod
    environment:
      VITE_APP_ENV: prod
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "127.0.0.1:3000:9443"
      - "127.0.0.1:3080:9080"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

  backend:
    container_name: backend_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports: ["127.0.0.1:5678:5678"] # Debug port
    environment:
      PYTHONPATH: /app
      APP_ENV: prod
      SECRET_KEY: yoursecretkey
      DB_URL: "postgresql+asyncpg://your_username:your_password@postgres_prod:5432/your_database_prod"
      CELERY_BROKER_URL: redis://redis_prod:6379/0
      REDIS_URL: redis://redis_prod:6379/0
      RUN_MIGRATIONS: true
    depends_on:
      - postgres
      - redis
      - celery
    volumes:
      - pdf_data:/app/data/pdfs

  postgres:
    image: pgvector/pgvector:pg14@sha256:fb27b00a92028f4749bf18f3d31b18fc62510258326486fb8900653ab2701252
    container_name: postgres_prod
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_prod
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  adminer:
    container_name: adminer_prod
    image: adminer:5.3.0@sha256:6bc678e77abcd8c7f34133f4903a4be485ec38b17df3d40a845ee56af0fcb32a
    restart: always
    ports:
      - 127.0.0.1:${ADMINER_PORT:-8080}:8080
    depends_on:
      - postgres

  redis:
    image: redis:7.4.5-alpine@sha256:0c0142c3cd69bc030ea09fecfa1c1c0c7d0e7d6081be6bb4957804f23d2cf57a
    container_name: redis_prod
    ports:
      - "127.0.0.1:6379:6379"
    volumes: 
      - redis_data:/data

  celery:
    container_name: celery_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: celery
    ports: ["127.0.0.1:5679:5679"]
    environment:
      PYTHONPATH: /app
      APP_ENV: prod
      SECRET_KEY: yoursecretkey
      DB_URL: "postgresql+asyncpg://your_username:your_password@postgres_prod:5432/your_database_prod"
      CELERY_BROKER_URL: redis://redis_prod:6379/0
      REDIS_URL: redis://redis_prod:6379/0
    depends_on:
      - redis
      - postgres
    volumes:
      - pdf_data:/app/data/pdfs

  flower:
    container_name: flower_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: uv run celery -A src.worker flower --port=5555
    environment:
      PYTHONPATH: /app
      APP_ENV: prod
      SECRET_KEY: yoursecretkey
      DB_URL: "postgresql+asyncpg://your_username:your_password@postgres_prod:5432/your_database_prod"
      CELERY_BROKER_URL: redis://redis_prod:6379/0
      REDIS_URL: redis://redis_prod:6379/0
    ports:
      - 127.0.0.1:${FLOWER_PORT:-5555}:5555
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
  pdf_data:
