services:
  postgres:
    image: pgvector/pgvector:pg14@sha256:fb27b00a92028f4749bf18f3d31b18fc62510258326486fb8900653ab2701252
    container_name: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5432:5432

  adminer:
      image: adminer:5.3.0@sha256:6bc678e77abcd8c7f34133f4903a4be485ec38b17df3d40a845ee56af0fcb32a
      restart: always
      ports:
        - 127.0.0.1:8080:8080

  redis:
    image: redis:7.4.5-alpine@sha256:0c0142c3cd69bc030ea09fecfa1c1c0c7d0e7d6081be6bb4957804f23d2cf57a
    ports:
      - 127.0.0.1:6379:6379
    volumes: 
      - redis_data:/data

  # celery:
  #   container_name: celery_${APP_ENV:-dev}
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-dev
  #     target: celery
  #   ports: ["5679:5679"]
  #   environment:
  #     PYTHONPATH: /app
  #     APP_ENV: ${APP_ENV:-dev}
  #     SECRET_KEY: yoursecretkey
  #     DB_URL: "postgresql+asyncpg://your_username:your_password@postgres_${APP_ENV:-dev}:5432/your_database_${APP_ENV:-dev}"
  #     CELERY_BROKER_URL: redis://redis_${APP_ENV:-dev}:6379/0
  #     REDIS_URL: redis://redis_${APP_ENV:-dev}:6379/0
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./server:/app

  # flower:
  #   container_name: flower_${APP_ENV:-dev}
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-dev
  #     target: server
  #   command: celery -A src.worker flower --port=5555
  #   environment:
  #     PYTHONPATH: /app
  #     APP_ENV: ${APP_ENV:-dev}
  #     SECRET_KEY: yoursecretkey
  #     DB_URL: "postgresql+asyncpg://your_username:your_password@postgres_${APP_ENV:-dev}:5432/your_database_${APP_ENV:-dev}"
  #     CELERY_BROKER_URL: redis://redis_${APP_ENV:-dev}:6379/0
  #     REDIS_URL: redis://redis_${APP_ENV:-dev}:6379/0
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #     - celery

volumes:
  postgres_data:
  redis_data: