FROM node:22-alpine@sha256:1b2479dd35a99687d6638f5976fd235e26c5b37e8122f786fcd5fe231d63de5b AS client

WORKDIR /app
ENV PYTHONPATH=/app

COPY client/package.json client/package-lock.json ./

RUN npm ci

COPY client/eslint.config.js .
COPY client/index.html .
COPY client/postcss.config.js .
COPY client/tailwind.config.js .
COPY client/tsconfig.json .
COPY client/tsconfig.app.json .
COPY client/tsconfig.node.json .
COPY client/vite.config.ts .

COPY client/public ./public
COPY client/src ./src

EXPOSE 3000
CMD ["npm", "run", "dev"]

FROM python:3.13-alpine@sha256:af1fd7a973d8adc761ee6b9d362b99329b39eb096ea3c53b8838f99bd187011e AS server

ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=/app
WORKDIR /app

COPY server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir debugpy

COPY server/ .

EXPOSE 8080 5678

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "fastapi", "dev", "src/main.py", "--host", "0.0.0.0", "--port", "8080"]

FROM python:3.13-alpine@sha256:af1fd7a973d8adc761ee6b9d362b99329b39eb096ea3c53b8838f99bd187011e AS celery

ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=/app
RUN addgroup -S celerygroup && adduser -S celeryuser -G celerygroup

WORKDIR /app

COPY server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir debugpy

COPY server/ .

RUN chown -R celeryuser:celerygroup /app
USER celeryuser

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5679", "-m", "celery", "-A", "src.worker", "worker", "--loglevel=info"]