"""Rename Project ID to UUID and LLM Config to Model config 

Revision ID: 1f7f425d7ec0
Revises: 79e2f6183e58
Create Date: 2025-07-11 07:19:01.942639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7f425d7ec0'
down_revision: Union[str, None] = '79e2f6183e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('project_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('file_project_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'project', ['project_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('file', 'project_id')
    op.add_column('job', sa.Column('llm_config', sa.JSON(), nullable=False))
    op.drop_column('job', 'model_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('model_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('job', 'llm_config')
    op.add_column('file', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_project_id_fkey'), 'file', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('file', 'project_uuid')
    # ### end Alembic commands ###
