"""fix missing revision

Revision ID: 8235f413f208
Revises: 1f7f425d7ec0
Create Date: 2025-07-21 06:47:15.469692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8235f413f208'
down_revision: Union[str, None] = '1f7f425d7ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobtask', sa.Column('doi', sa.String(length=255), nullable=False))
    op.drop_column('jobtask', 'paper_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobtask', sa.Column('paper_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('jobtask', 'doi')
    # ### end Alembic commands ###
