"""combine inclusion_criteria and exclusion_criteria columns to one criteria column. change criteria to use jsonb format instead of text.

Revision ID: 84c8ca59d0ac
Revises: efab11cd8cc0
Create Date: 2025-08-07 08:41:41.658037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84c8ca59d0ac'
down_revision: Union[str, None] = 'efab11cd8cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('project', 'inclusion_criteria')
    op.drop_column('project', 'exclusion_criteria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('exclusion_criteria', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('inclusion_criteria', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('project', 'criteria')
    # ### end Alembic commands ###
