"""Add constraint to File UUID in Paper model

Revision ID: 8dac50fec995
Revises: ba2916cfcc4b
Create Date: 2025-08-14 19:17:06.430847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dac50fec995'
down_revision: Union[str, None] = 'ba2916cfcc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_file_uuid', 'paper', ['file_uuid'])
    op.create_foreign_key(None, 'paper', 'file', ['file_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.drop_constraint('uq_file_uuid', 'paper', type_='unique')
    # ### end Alembic commands ###
