"""Convert ID to UUID

Revision ID: cb925b82cfb0
Revises: 85d387c239dd
Create Date: 2025-08-22 07:59:30.827767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb925b82cfb0'
down_revision: Union[str, None] = '85d387c239dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobtask', sa.Column('paper_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('jobtask_paper_id_fkey'), 'jobtask', type_='foreignkey')
    op.create_foreign_key(None, 'jobtask', 'paper', ['paper_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('jobtask', 'paper_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobtask', sa.Column('paper_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobtask', type_='foreignkey')
    op.create_foreign_key(op.f('jobtask_paper_id_fkey'), 'jobtask', 'paper', ['paper_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jobtask', 'paper_uuid')
    # ### end Alembic commands ###
