"""Paper ID for job task

Revision ID: 85d387c239dd
Revises: 3c9c6f12b16c
Create Date: 2025-08-22 07:51:45.986000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d387c239dd'
down_revision: Union[str, None] = '3c9c6f12b16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobtask', sa.Column('paper_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobtask', 'paper', ['paper_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobtask', type_='foreignkey')
    op.drop_column('jobtask', 'paper_id')
    # ### end Alembic commands ###
