"""Change project_uuid to job_id in Paper model

Revision ID: f2234665eb51
Revises: c49c92989df6
Create Date: 2025-08-13 11:05:57.946921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2234665eb51'
down_revision: Union[str, None] = 'c49c92989df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('job_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_project_paper_id'), 'paper', type_='unique')
    op.create_unique_constraint('uq_job_paper_id', 'paper', ['job_id', 'paper_id'])
    op.drop_constraint(op.f('paper_project_uuid_fkey'), 'paper', type_='foreignkey')
    op.create_foreign_key(None, 'paper', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('paper', 'project_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('project_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.create_foreign_key(op.f('paper_project_uuid_fkey'), 'paper', 'project', ['project_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('uq_job_paper_id', 'paper', type_='unique')
    op.create_unique_constraint(op.f('uq_project_paper_id'), 'paper', ['project_uuid', 'paper_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('paper', 'job_id')
    # ### end Alembic commands ###
