"""Remove UniqueConstraint from Paper model

Revision ID: 6124383eceac
Revises: 8dac50fec995
Create Date: 2025-08-14 20:07:57.507882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6124383eceac'
down_revision: Union[str, None] = '8dac50fec995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_file_uuid'), 'paper', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_file_uuid'), 'paper', ['file_uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
