"""Prompting config for Job

Revision ID: a96acd3ca662
Revises: f967bdc7fa50
Create Date: 2025-09-22 10:25:47.885438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a96acd3ca662'
down_revision: Union[str, None] = 'f967bdc7fa50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


prompting_type_enum = sa.Enum(
    "ONE_SHOT", "ZERO_SHOT", "FEW_SHOT", name="prompting_type"
)

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('prompting_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('job', 'prompting_type')
    prompting_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('prompting_type', postgresql.ENUM('ONE_SHOT', 'ZERO_SHOT', 'FEW_SHOT', name='prompting_type'), autoincrement=False, nullable=False))
    op.drop_column('job', 'prompting_config')
    # ### end Alembic commands ###
