"""Make doi optional for paper

Revision ID: eacfbb93fec2
Revises: 3c2bfbac13d4
Create Date: 2025-09-23 14:13:09.964818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eacfbb93fec2"
down_revision: Union[str, None] = "3c2bfbac13d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("paper", "doi", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("paper", "doi", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
