"""Make doi optional

Revision ID: 3c2bfbac13d4
Revises: 46b8a212a152
Create Date: 2025-09-23 13:58:59.728373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2bfbac13d4'
down_revision: Union[str, None] = '46b8a212a152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobtask', 'doi',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobtask', 'doi',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
