"""Add error for JobTask model

Revision ID: 6e6fe5091797
Revises: eacfbb93fec2
Create Date: 2025-12-08 11:45:24.334772

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e6fe5091797"
down_revision: Union[str, None] = "eacfbb93fec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobtask", sa.Column("error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobtask", "error")
    # ### end Alembic commands ###
