"""Switch SQLAlchemy to use Mapped

Revision ID: a7d869b16346
Revises: 6e6fe5091797
Create Date: 2025-12-17 08:24:55.819284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d869b16346'
down_revision: Union[str, None] = '6e6fe5091797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setting', 'secret',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setting', 'secret',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
