"""add_celery_task_id_to_job

Revision ID: ec09219baf8d
Revises: a7d869b16346
Create Date: 2026-02-23 13:55:34.097658

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec09219baf8d"
down_revision: Union[str, None] = "a7d869b16346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("celery_task_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "celery_task_id")
    # ### end Alembic commands ###
