"""Add classification embedding and visualization tables

Revision ID: bb2cd85b9511
Revises: a7d869b16346
Create Date: 2026-02-17 16:52:36.760558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb2cd85b9511'
down_revision: Union[str, None] = 'a7d869b16346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('systematic_review_context', sa.Text(), nullable=False),
    sa.Column('classifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('embedding_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt_prefix', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('visualization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visualization_type', sa.String(length=50), server_default='umap_embedding', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('source_job_uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('job', sa.Column('job_type', sa.String(length=50), server_default='screening', nullable=False))
    op.add_column('job', sa.Column('classification_config_id', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('embedding_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job', 'classification_config', ['classification_config_id'], ['id'])
    op.create_foreign_key(None, 'job', 'embedding_config', ['embedding_config_id'], ['id'])
    op.add_column('paper', sa.Column('embedding_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('paper', sa.Column('classification_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'classification_cache')
    op.drop_column('paper', 'embedding_vector')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'embedding_config_id')
    op.drop_column('job', 'classification_config_id')
    op.drop_column('job', 'job_type')
    op.drop_table('visualization')
    op.drop_table('embedding_config')
    op.drop_table('classification_config')
    # ### end Alembic commands ###
