"""

Revision ID: 9f595e1b5aa5
Revises: 77dd0f7b899d
Create Date: 2026-05-18 06:53:23.377006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f595e1b5aa5"
down_revision: Union[str, None] = "77dd0f7b899d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("owner_uuid", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "project", "user", ["owner_uuid"], ["uuid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_column("project", "owner_uuid")
    # ### end Alembic commands ###
