"""add check constraint requiring paper to have a source file

Revision ID: 746cfb84e83f
Revises: 8e0735c28850
Create Date: 2026-07-09 13:17:15.946923

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '746cfb84e83f'
down_revision: Union[str, None] = '8e0735c28850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("ck_paper_has_source_file", "paper", "file_uuid IS NOT NULL OR pdf_file_uuid IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_paper_has_source_file", "paper", type_="check")
    # ### end Alembic commands ###
