"""add storage path to file and add pdf file uuid and make file uuid nullable in paper

Revision ID: 8e0735c28850
Revises: add_consent_fields_to_user
Create Date: 2026-07-09 13:13:50.588981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0735c28850'
down_revision: Union[str, None] = 'add_consent_fields_to_user'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('storage_path', sa.String(length=255), nullable=True))
    op.add_column('paper', sa.Column('pdf_file_uuid', sa.UUID(), nullable=True))
    op.alter_column('paper', 'file_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'paper', 'file', ['pdf_file_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.alter_column('paper', 'file_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('paper', 'pdf_file_uuid')
    op.drop_column('file', 'storage_path')
    # ### end Alembic commands ###
