"""add pdf_file_uuid to jobtask and screening_mode to job

Revision ID: 1471cffe558b
Revises: 746cfb84e83f
Create Date: 2026-07-13 11:37:53.929751

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1471cffe558b"
down_revision: Union[str, None] = "746cfb84e83f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

job_screening_mode_enum = sa.Enum("TEXT", "PDF", name="jobscreeningmode")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    job_screening_mode_enum.create(bind, checkfirst=True)
    op.add_column(
        "job",
        sa.Column(
            "screening_mode",
            job_screening_mode_enum,
            nullable=False,
            server_default="TEXT",
        ),
    )
    op.add_column("jobtask", sa.Column("pdf_file_uuid", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "jobtask", "file", ["pdf_file_uuid"], ["uuid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_constraint(None, "jobtask", type_="foreignkey")
    op.drop_column("jobtask", "pdf_file_uuid")
    op.drop_column("job", "screening_mode")
    job_screening_mode_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
