"""add automatic screening mode option

Revision ID: a654eda7ca2f
Revises: 78dc8d91e2be
Create Date: 2026-07-21 14:01:15.726511

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a654eda7ca2f"
down_revision: Union[str, None] = "78dc8d91e2be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE jobscreeningmode ADD VALUE 'AUTOMATIC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
