"""add criteria embeddings to project and pdf chunk embedding table

Revision ID: 78dc8d91e2be
Revises: 1471cffe558b
Create Date: 2026-07-20 10:34:58.135369

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78dc8d91e2be"
down_revision: Union[str, None] = "1471cffe558b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdf_chunk_embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("pdf_file_uuid", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pdf_file_uuid"], ["file.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pdf_file_uuid", "chunk_index", name="uq_pdf_chunk_index"),
        sa.UniqueConstraint("uuid"),
    )
    op.add_column(
        "project",
        sa.Column(
            "inclusion_criteria_embedding",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "project",
        sa.Column(
            "exclusion_criteria_embedding",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "exclusion_criteria_embedding")
    op.drop_column("project", "inclusion_criteria_embedding")
    op.drop_table("pdf_chunk_embedding")
    # ### end Alembic commands ###
