"""set null on jobtask pdf_file_uuid delete

Revision ID: 92167d045d4c
Revises: a654eda7ca2f
Create Date: 2026-08-10 11:08:04.728500

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '92167d045d4c'
down_revision: Union[str, None] = 'a654eda7ca2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobtask_pdf_file_uuid_fkey'), 'jobtask', type_='foreignkey')
    op.create_foreign_key(None, 'jobtask', 'file', ['pdf_file_uuid'], ['uuid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobtask', type_='foreignkey')
    op.create_foreign_key(op.f('jobtask_pdf_file_uuid_fkey'), 'jobtask', 'file', ['pdf_file_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
