"""add screening target to project

Revision ID: 659467a3f575
Revises: add_consent_fields_to_user
Create Date: 2026-08-10 08:34:32.295337

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "659467a3f575"
down_revision: Union[str, None] = "add_consent_fields_to_user"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "screening_target",
            sa.String(length=32),
            nullable=False,
            server_default="PAPER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "screening_target")
    # ### end Alembic commands ###
