"""Rename model_config to llm_config

Revision ID: 3e349f45bfa8
Revises: a9582f8f8129
Create Date: 2025-07-04 13:47:21.323301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e349f45bfa8'
down_revision: Union[str, None] = 'a9582f8f8129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('llm_config', sa.JSON(), nullable=False))
    op.drop_column('job', 'model_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('model_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('job', 'llm_config')
    # ### end Alembic commands ###
