"""change project_id to project_uuid in file schema and crud

Revision ID: 8f70becf20ff
Revises: c7e1d11c725c
Create Date: 2025-07-09 13:58:51.303742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f70becf20ff'
down_revision: Union[str, None] = 'c7e1d11c725c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('project_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('file_project_id_fkey'), 'file', type_='foreignkey')
    op.drop_column('file', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('file_project_id_fkey'), 'file', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('file', 'project_uuid')
    # ### end Alembic commands ###
