apiVersion: v1
kind: Secret
metadata:
  name: aisysrev-secret
  namespace: aisysrev
type: Opaque
stringData:
  DB_URL: postgresql+asyncpg://<user>:<password>@<db-host>:5432/<database-name>?ssl=require
  OIDC_CLIENT_ID: <entity-id-from-sp-registry>
  OIDC_CLIENT_SECRET: <client-secret-from-sp-registry>
  SECRET_KEY: <random-hex-string>

---

apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  namespace: aisysrev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths": {"quay.io": {"username": "<username>","password": "<password>","auth":"base64("username:password")"}}}
