name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
        working-directory: client
      - name: Build client
        run: npm run build
        working-directory: client
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: client
      - name: Run Typecheck
        run: npx tsc --noEmit
        working-directory: client
      - name: Run ESLint
        run: npm run lint
        working-directory: client
      - name: Start Docker Compose stack
        run: FRONTEND_PORT=3002 FLOWER_PORT=5557 ADMINER_PORT=8082 APP_ENV=test docker compose -f docker-compose-dev.yml -p test up -d --build
      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/docs; then
              echo "Backend is up!";
              break;
            fi
            echo "Waiting for backend...";
            sleep 2
          done
      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test
        working-directory: client
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
