name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
           node-version-file: '.nvmrc'
      - name: Client - Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ runner.os }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: Client - Install dependencies
        run: npm ci --cache ~/.npm
        working-directory: client
      - name: Client - Run Typecheck
        run: npm run typecheck
        working-directory: client
      - name: Client - Run ESLint
        run: npm run lint
        working-directory: client
  build:
    runs-on: ubuntu-latest
    needs: lint-typecheck
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
           node-version-file: '.nvmrc'
      - name: Client - Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ runner.os }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: Client - Install dependencies
        run: npm ci --cache ~/.npm
        working-directory: client
      - name: Client - Build client
        run: npm run build
        working-directory: client
  backend-test:
    runs-on: ubuntu-latest
    needs: test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: your_username
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: your_database_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U your_username"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7.4.5-alpine
        ports:
          - 6379:6379
      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: your_username
          MINIO_ROOT_PASSWORD: minio-secret-key
        ports:
          - 9000:9000
          - 9001:9001
        options: >-
          --entrypoint minio
          --health-cmd="curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          server /data --console-address ":9001"
    env:
      APP_ENV: test
      DB_URL: postgresql+asyncpg://your_username:your_password@postgres:5432/your_database_test
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: your_username
      MINIO_ROOT_PASSWORD: minio-secret-key
      MINIO_BUCKET: llm-screening-poc-bucket
      SECRET_KEY: yoursecretkey
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: pip install --upgrade pip && pip install -r server/requirements.txt

      - name: Wait for Postgres
        run: |
          until pg_isready -h postgres -U your_username; do
            sleep 1
          done

      - name: Run Alembic migrations
        run: alembic upgrade head
        working-directory: server

      - name: Run backend pytest
        run: pytest --maxfail=1 --disable-warnings --cov=src
        working-directory: server

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: server/htmlcov/
  e2e-test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 60
    env:
      APP_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
           node-version-file: '.nvmrc'
      - name: Client - Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ runner.os }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: Client - Install dependencies
        run: npm ci --cache ~/.npm
        working-directory: client
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: client
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: client
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30
